name: Create Signed Encrypted Transmission Archive

on:
  release:
    types: [created]

jobs:
  zip-and-attach:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get the version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Zip transmission folder
        run: zip -r transmission-signee-chiffree-${{ steps.get_version.outputs.VERSION }}.zip transmission-signee-chiffree/

      - name: Generate SHA256 checksum
        run: sha256sum transmission-signee-chiffree-${{ steps.get_version.outputs.VERSION }}.zip > transmission-signee-chiffree-${{ steps.get_version.outputs.VERSION }}.zip.sha256

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            transmission-signee-chiffree-${{ steps.get_version.outputs.VERSION }}.zip
            transmission-signee-chiffree-${{ steps.get_version.outputs.VERSION }}.zip.sha256
