# Updated .github/workflows/zip-release.yml
name: Créer archive pour transmission-signee-chiffree

on:
  release:
    types: [created]

jobs:
  zip-and-attach:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Zip transmission folder
        run: zip -r transmission-signee-chiffree.zip transmission-signee-chiffree/

      - name: Generate SHA256 checksum
        run: sha256sum transmission-signee-chiffree.zip > transmission-signee-chiffree.zip.sha256

      - name: Upload Files to release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            transmission-signee-chiffree.zip
            transmission-signee-chiffree.zip.sha256
